# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58c4a786708a9d5781d4f514c3ff5520f167d5b7a2f0f25a57f97b688717ce68361e0dfe17d95d2f4fd07da25a23ca98c276a7b461765a97ee46fc4ed4c87d11

test:
  secret_key_base: 60fec4e9f9d550a6aa120b2fde96546415d6220ac95e5c3ff8310d332a0054da69f039274bf21adf9686459bbde5167994ce5486bbf87cd6029256c8e65e4637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
